name: conai
services:
  api:
    build:
      context: ./backend
      target: development
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - conai
  frontend:
    build:
      context: ./frontend
      target: development
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - conai
    command: npm run dev
    depends_on:
      - api
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - conai
    depends_on:
      - api
      - frontend

volumes:
  caddy_data:
  caddy_config:

networks:
  conai:
    driver: bridge
