"use client";
// import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { NavigationMenuDemo } from "@/components/navbar/NavBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const excludeLinks = ["/"];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const window = globalThis.window;
  return (
    <html lang="en" className="lg:mx-auto lg:container">
      <head>
        <title>ConAI</title>
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {excludeLinks.includes(window.location.pathname) && (
          <div className=" h-[70px] sticky bg-transparent shadow-lg rounded-lg flex p-5 z-10">
            <NavigationMenuDemo />
          </div>
        )}
        <div className="justify-center items-center flex">{children}</div>
      </body>
    </html>
  );
}
